#!/bin/bash

# This file is part of cfg.msh by Martin Richard
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

# load scripts compatible with both shells
local script
for script in $MSH_CFG_PATH/scripts/*.msh; do source $script; done

# Shell running the script
if [ -z "$MSH_SHELL" ]
then
  MSH_SHELL=`shellname`
fi

# Load scripts specific to current shell
for script in $MSH_CFG_PATH/scripts/*.$MSH_SHELL; do source $script; done
