#!/bin/bash

# This file is part of cfg.msh by Martin Richard
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

git update-index --assume-unchanged local_aliases

echo -n "Fetching submodules... "
git submodule init > /dev/null 2>&1
git submodule update > /dev/null 2>&1
echo "ok"
echo

echo -n "Setup zsh... "
ln -s /opt/cfg.msh/mshrc ~/.zshrc
chsh -s `which zsh`
echo "ok"
echo
